server:
  port: 8080

jwt:
  public_key: file:auth_service/secrets/public_key.pem
  private_key: file:auth_service/secrets/private_key.pem
  lifetime: 24h

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: auth_service